### ISSUE TITLE
npm install modelar-oracle-adpater    err

### ISSUE THREAD

**Issue by 120520** [Hyurl/modelar-oracle-adapter#1]
Since `node-oracledb` requires some prerequisites before installing, you must 
prepare you machine as its
[documentation](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)
says. You could try to install it before installing `modelar-oracle-adpater`, 
that guarantees a successful installation.

If you couldn't understand what `node-oracledb` doc says, please mail me to ayon@hyurl.com, I have some experience.

**Comment by 120520** [comment]
@latest  找不到 ,0.1.1找不到,0.1.0  也找不到.......

**Comment by 120520** [comment]
@Hyurl npm install modelar-oracle-adpater   404 err

**Comment by Hyurl** [comment]
发布有错误，我更新一下

**Comment by Hyurl** [comment]
已经更新了，现在应该可以正常安装了，之前模块名字拼错了

**Comment by 120520** [comment]
good
